### ISSUE TITLE
冒昧问下每个项目的作用分别是什么

### ISSUE THREAD

**Issue by RustRw** [yaobaiwei/PregelPlus#1]
看到有好几个关于图相关的项目, 冒昧问下这些项目分别的不同点是什么

**Comment by yaobaiwei** [comment]
有一些是用来做离线图计算的（又分成基于内存的,e.g.,Pregel+和基于磁盘的, e.g., GraphD，etc），有些是用来做在线图查询的（e.g., Grasper）。详情可阅读每个repo下的README、toturial以及项目网站。

**Comment by yaobaiwei** [comment]
> 看到有好几个关于图相关的项目, 冒昧问下这些项目分别的不同点是什么

**Comment by yaobaiwei** [comment]
> 看到有好几个关于图相关的项目, 冒昧问下这些项目分别的不同点是什么

有一些是用来做离线图计算的（又分成基于内存的,e.g.,Pregel+和基于磁盘的, e.g., GraphD，etc），有些是用来做在线图查询的（e.g., Grasper）。详情可阅读每个repo下的README、toturial以及项目网站。
